apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoworkflows
  namespace: argo
  labels:
    app: argoworkflows
spec:
  project: default
  source:
    repoURL: https://github.com/filipSamanek/skoleni
    targetRevision: HEAD
    path: argo/workflows
  destination:
    name: in-cluster
    namespace: argo
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true

